### ISSUE TITLE
YSI

### ISSUE THREAD

**Issue by GasmanVN** [Southclaw/SIF#17]
Why SIF include is #include <YSI_4\y_hooks> not #include <YSI\y_hooks>

**Comment by Southclaw** [comment]
Not sure if your post content was lost but this makes no sense...

**Comment by GasmanVN** [comment]
Edit
Why SIF include is #include <YSI_4\...> not #include <YSI_4\..>

**Comment by GasmanVN** [comment]
Why SIF include is #include YSI_4 not #include YSI

**Comment by Southclaw** [comment]
It's just left over from the conversion back when I had both YSI versions.
